mysite/music/urls.py
from django.conf.urls import url

from . import views

app_name = 'music'

urlpatterns = [
    #/music/
    url(r'^$', views.IndexView.as_view(), name='index'),
    #/music/
    url(r'^register/$', views.UserFormView.as_view(), name='register'),

    #/music/<album_di>/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail' ),
    #/music/album/add
    url(r'album/add/$', views.AlbumCreate.as_view(), name='album-add'),
 
    #/music/album/2/
    url(r'album/(?P<pk>[0-9]+)/$', views.AlbumUpdate.as_view(), name='album-update'),

    #/music/album/2/delete
    url(r'album/(?P<pk>[0-9]+)/delete/$', views.AlbumDelete.as_view(), name='album-delete'),


]



#
#urlpatterns = [
#    #/music/
#    url(r'^$', views.index, name='index'),
#
#    #/music/<album_di>/
#    url(r'^(?P<album_id>[0-9]+)/$', views.detail, name='detail' ),
#
#]

mysite/mysite/music/urls.py
from django.conf.urls import url

from . import views

app_name = 'music'

urlpatterns = [
    #/
    url(r'^$', views.IndexView.as_view(), name='index'),
    #/test/pk
    url(r'^test/$', views.test, name='test'),
    #/test/pk
    url(r'test/(?P<pk>[0-9]+)/$', views.testDetail, name='testDetail'),

    #/register
    url(r'^register/$', views.UserFormView.as_view(), name='register'),

    #/<album_di>/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail' ),
    #/album/add
    url(r'album/add/$', views.AlbumCreate.as_view(), name='album-add'),

    #/album/2/
    url(r'album/(?P<pk>[0-9]+)/$', views.AlbumUpdate.as_view(), name='album-update'),

    #/album/2/delete
    url(r'album/(?P<pk>[0-9]+)/delete/$', views.AlbumDelete.as_view(), name='album-delete'),


]





#
#urlpatterns = [
#    #/music/
#    url(r'^$', views.index, name='index'),
#
#    #/music/<album_di>/
#    url(r'^(?P<album_id>[0-9]+)/$', views.detail, name='detail' ),
#
#]

mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^music/', include('music.urls')),
    url(r'^admin/', admin.site.urls),
]

#use local folder for storing files when we are in DEBUG mode.
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/mysite/music/models.py
from __future__ import unicode_literals

from django.db import models
from django.core.urlresolvers import reverse
# Create your models here.

class Album(models.Model):
    # read about OOP and MVC
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.FileField()

    def get_absolute_url(self):
        return reverse('music:detail', args=[self.pk])

    def __str__(self):
        # read about string concatenation
        return self.album_title + ' - ' + self.artist

class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)
    #sting represantation of our songs.
    def __str__(self):
        return self.song_title

mysite/music/views.py
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.views import generic
from django.views.generic import View
from .models import Album
from .forms import UserForm


class IndexView(generic.ListView):
    template_name = 'music/index.html'
    context_object_name = 'all_albums'

    def get_queryset(self):
        return Album.objects.all()

class DetailView(generic.DetailView):
    model = Album
    template_name = 'music/detail.html'

class AlbumCreate(CreateView):
    model = Album
    # what fields do you need.
    fields = ['artist', 'album_title', 'genre', 'album_logo']

class AlbumUpdate(UpdateView):
    model = Album
    # what fields do you need.
    fields = ['artist', 'album_title', 'genre', 'album_logo']
    success_url = "/music/"

class AlbumDelete(DeleteView):
    model = Album
    success_url = reverse_lazy('music:index')

class UserFormView(View):
    #importing from our forms file
    form_class = UserForm
    template_name = 'music/registration_form.html'

    #display blank form
    def get(self, request):
        #We want to show empty form.
        form = self.form_class(None)
        #we are rendering empty html form. Our template gets
        #form object.
        return render(request, self.template_name, {'form': form })

    # process form data
    def post(self, request):
        #We want to submit filled form
        #request.POST will have all information.
        form = self.form_class(request.POST)

        if form.is_valid():

            #it will create an Object from the form.
            #we are storing in localy for now.
            user = form.save(commit=False)
            # cleaned (normalized) data
            # for example you want the same day format.
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            # whenever you are changing user password
            # u need to use set_password function
            # djnago will has it for you.
            user.set_password(password)
            user.save()

            #this functions check database if this user actually exist.
            user = authenticate(username=username, password=password)
            #returns User object if credentials are correct

            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('music:index')
        return render(request, self.template_name, {'form': form })







#{% url 'music:album-delete' album.id %}

mysite/mysite/music/views.py
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.views import generic
from django.views.generic import View
from .models import Album
from .forms import UserForm
from django.http import HttpResponse



def testDetail(request, pk):
    return HttpResponse("<h1> Test View:  " +str(pk) + "</h1>")

def test(request):
    return render(request, 'music/test.html')

class IndexView(generic.ListView):
    template_name = 'music/index.html'
    context_object_name = 'all_albums'

    def get_queryset(self):
        return Album.objects.all()

class DetailView(generic.DetailView):
    model = Album
    template_name = 'music/detail.html'

class AlbumCreate(CreateView):
    model = Album
    # what fields do you need.
    fields = ['artist', 'album_title', 'genre', 'album_logo']

class AlbumUpdate(UpdateView):
    model = Album
    # what fields do you need.
    fields = ['artist', 'album_title', 'genre', 'album_logo']
    success_url = "/music/"

class AlbumDelete(DeleteView):
    model = Album
    success_url = reverse_lazy('music:index')

class UserFormView(View):
    #importing from our forms file
    form_class = UserForm
    template_name = 'music/registration_form.html'

    #display blank form
    def get(self, request):
        #We want to show empty form.
        form = self.form_class(None)
        #we are rendering empty html form. Our template gets
        #form object.
        return render(request, self.template_name, {'form': form })

    # process form data
    def post(self, request):
        #We want to submit filled form
        #request.POST will have all information.
        form = self.form_class(request.POST)

        if form.is_valid():

            #it will create an Object from the form.
            #we are storing in localy for now.
            user = form.save(commit=False)
            # cleaned (normalized) data
            # for example you want the same day format.
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            # whenever you are changing user password
            # u need to use set_password function
            # djnago will has it for you.
            user.set_password(password)
            user.save()

            #this functions check database if this user actually exist.
            user = authenticate(username=username, password=password)
            #returns User object if credentials are correct

            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('music:index')
        return render(request, self.template_name, {'form': form })







#{% url 'music:album-delete' album.id %}

mysite/mysite/music/templates/music/album_form.html
{% extends 'music/base.html' %}
{% block title %} Add an New Album {% endblock %}
{% block albums_active %} active {% endblock %}

{% block body %}
<div class="container-fluid">

  <div class="row">

    <div class="col-sm-12 col-md-7">
      <div class="panel panel-default">
        <div class="panel-body">
            <form class="form-horizontal" action="" method="post" ectype="multipart/form-data">
              {% csrf_token %}
              {% include 'music/form-template.html'%}
              <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                  <button type="submit" class="btn btn-success">Submit !</button>
                </div>

              </div>
            </form>


        </div>
      </div>
    </div>

  </div>


</div>
{% endblock %}

mysite/mysite/music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title> {% block title %} Music Cloud {% endblock %} </title>
  <!-- Latest compiled and minified CSS -->
  <!-- Loads the path to your static files -->
  {% load staticfiles %}
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet" type='text/css'>
  <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

</head>
<body>
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <!--Header -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
         </button>
        <a class="navbar-brand" href="{% url 'music:index' %}"> Sound Cloud</a>
      </div>
      <!--Items -->
      <div class="collapse navbar-collapse" id="topNavBar">
          <ul class="nav navbar-nav">
            <li class=" ">
              <a href="{% url 'music:index' %}">
                <span class="glyphicon glyphicon-cd" aria-hidden="True"></span>
                  Albums
              </a>
            </li>
            <li class="">
              <a href="#">
                <span class="glyphicon glyphicon-music" aria-hidden="True"></span>
                  Songs
              </a>
            </li>
          </ul>

          <form class="navbar-form navbar-left" role="search" action="#">
              <div class="form-group">
                  <input type="text" class="form-control" name="q" value="">
              </div>
              <button type="submit" class="btn btn-default">Search</button>
          </form>

          <ul class="nav navbar-nav navbar-right">
            <li class="">
              <a href="{% url 'music:album-add'%}">
                <span class="glyphicon glyphicon-plus" aria-hidden="True"></span>
                  Add Album
              </a>
            </li>
            <li class="">
              <a href="#">
                <span class="glyphicon glyphicon-off" aria-hidden="True"></span>
                  Log Out
              </a>
            </li>
          </ul>
      </div>
    </div>
  </nav>
{% block body %}
{% endblock %}
 </body>
</html>

mysite/mysite/music/templates/music/detail.html
{%  extends 'music/base.html' %}
{% block title %} Album {% endblock %}
{% block body %}
<img src ="{{ album.album_logo.url }}">

<h1> {{album.album_title}} </h1>
<h2>{{album.artist}}</h2>

{% for song in album.song_set.all %}
      {{song.song_title}}
      {% if song.is_favorite%}
        <img src="http://i.imgur.com/b9b13Rd.png"/>
      {% endif  %}
        <br>
  {% endfor %}
{% endblock %}

mysite/mysite/music/templates/music/form-template.html
{% for field in form %}
<!-- We are geting form object from our Views.class AlbumCreate(CreateView) -->
  <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <span class="text-danger small">{{field.errors}}</span>
      </div>
      <label class="control-label col-sm-2">{{field.label_tag}}</label>
      <div class="col-sm-10">{{field}}</div>
  </div>

{% endfor %}

mysite/mysite/music/templates/music/index.html
{% extends 'music/base.html' %}

{% block body %}

<div class="albums-container container-fluid">

    <!-- Albums -->
    <div class="row">

                {% for album in all_albums %}
                <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">
                        <a href="{% url 'music:detail' album.id %}">
                            <img src="{{ album.album_logo.url }}" class="img-responsive">
                        </a>
                        <div class="caption">
                            <h2>{{ album.album_title }}</h2>
                            <h4>{{ album.artist }}</h4>

                            <!-- View Details -->
                            <a href="{% url 'music:detail' album.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>

                            <!-- Delete Album -->
                            <form action="{% url 'music:album-delete' album.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="album_id" value="{{ album.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>

                            <!-- Favorite Album -->
                            <a href="#" class="btn btn-default btn-sm btn-favorite" role="button">
                                <span class="glyphicon glyphicon-star"></span>
                            </a>

                        </div>
                    </div>
                </div>

            {% endfor %}

    </div>
</div>

{% endblock %}

mysite/mysite/music/templates/music/registration_form.html
{% extends 'music/base.html' %}
{% block title %} Register {% endblock %}


{% block body %}
<div class="container-fluid">

  <div class="row">

    <div class="col-sm-12 col-md-7">
      <div class="panel panel-default">
        <div class="panel-body">
          <h3> Create a new Account </h3>
            <form class="form-horizontal" action="" method="post" ectype="multipart/form-data">
              {% csrf_token %}
              {% include 'music/form-template.html'%}
              <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                  <button type="submit" class="btn btn-success">Submit</button>
                </div>

              </div>
            </form>


        </div>
      </div>
    </div>

  </div>


</div>
{% endblock %}